# --- Estética Visual ---
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
font_size        11.2

# Sin redondeos, totalmente cuadrado
window_margin_width 0
window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0

# --- Esquema de Colores (Bosque Terminal) ---
background #0D100E
foreground #D1D5D2

# Cursor
cursor #607A6D
cursor_shape block

# Selección
selection_background #252D28
selection_foreground #D1D5D2

# Paleta ANSI (16 colores)
# Negro / Negro Brillante
color0 #0D100E
color8 #252D28

# Rojo / Rojo Brillante
color1 #7A6663
color9 #9E8A88

# Verde / Verde Brillante
color2 #607A6D
color10 #85A394

# Amarillo / Amarillo Brillante
color3 #7A755D
color11 #A39E85

# Azul / Azul Brillante
color4 #5D6A7A
color12 #8593A3

# Magenta / Magenta Brillante
color5 #6D607A
color13 #9385A3

# Cian / Cian Brillante
color6 #5D7A7A
color14 #85A3A3

# Blanco / Blanco Brillante
color7 #D1D5D2
color15 #E1E3DE
